#!/bin/bash
aws s3 cp s3://sheynkman-lab-lifebit/Reference/gencode.v35.annotation.canonical.gtf . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/gencode.v35.pc_transcripts.fa . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/gencode.v35.pc_translations.fa . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/GRCh38.primary_assembly.genome.canonical.fa . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/Human_Hexamer.tsv . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/Human_logitModel.RData . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/NEB_primers.fasta . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/chrLength.txt  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/chrNameLength.txt  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/chrStart.txt  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/echrName.txt  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/exonGeTrInfo.tab  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/exonInfo.tab  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/geneInfo.tab  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/Genome . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/genomeParameters.txt  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/Log.out . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/SAindex . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/SA . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/sjdbInfo.txt  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/sjdbList.fromGTF.out.tab  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/sjdbList.out.tab  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/star_index/star_genome/transcriptInfo.tab  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/Task1SearchTaskconfig_orf.toml . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Reference/uniprot_reviewed_canonical_and_isoform.fasta . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/illumina_data/jurkat_r1.fastq.gz . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/illumina_data/jurkat_r2.fastq.gz . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/jurkat_gene_kallisto.tsv . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/jurkat_merged.ccs.bam . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/kallist_table_rdeplete_jurkat.tsv . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac1.raw  . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac10.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac11.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac12.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac13.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac14.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac15.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac16.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac17.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac18.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac19.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac2.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac20.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac21.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac22.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac23.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac24.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac25.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac26.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac27.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac28.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac3.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac4.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac5.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac6.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac7.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac8.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/mass_spec/120426_Jurkat_highLC_Frac9.raw . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/SQANTI/jurkat_classification.txt . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/SQANTI/jurkat_corrected.fasta . --no-sign-request
aws s3 cp s3://sheynkman-lab-lifebit/Sample-Data/JURKAT/SQANTI/jurkat_corrected.gtf . --no-sign-request
